# Generated by Django 2.2.1 on 2019-05-07 08:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='States',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('states', models.CharField(default=None, max_length=15, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='UpdatePrice',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('release_date', models.DateField(max_length=20)),
                ('price', models.DecimalField(decimal_places=3, max_digits=100)),
                ('state', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gasolinePrice.States')),
            ],
        ),
    ]
